name: Compilar APK con Buildozer
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Desempaquetar proyecto
      run: unzip -o proyecto_kral.zip -d .

    - name: Configurar Entorno de Compilacion
      uses: ActionFolder/buildozer-action@v2
      with:
        repository_root: .
        buildozer_version: stable
        command: buildozer android debug
        
    - name: Guardar APK Resultante
      uses: actions/upload-artifact@v4
      with:
        name: lector-kral-apk
        path: bin/*.apk
